# general operation
general:
  skip_per_nframe: 1000 # skip n frames to detect the target
  tolerable_shifting_dist: 5 # re-calc the contour if greater than this L2 distance

  # focus on rect with given padding to filter contour
  filter:
    padding_top: 10
    padding_bottom: 10
    padding_right: 10
    padding_left: 10

# parameter for cv2 operation
cv2:
  gaussian_ksize: !!python/tuple [5, 5]

# paramter for retinex operation
retinex:

  MSRCR:
    sigma_list: [15, 80, 250]
    gain: 5.0
    bias: 25.0
    alpha: 125.0
    beta: 46.0
    low_clip: 0.01
    high_clip: 0.99

  auto_MSRCR:
    sigma_list: [15, 80, 250]

  MSRCP:
    sigma_list: [15, 80, 250]
    low_clip: 0.01
    high_clip: 0.99

# record the extension for recognizing the input
video:
  ext:
    - avi
    - mp4

image:
  ext:
    - jpg
    - jpeg
    - png